export const products = [
  {
    id: 1,
    img: "/img/prod/prod1.jpg",
    name: "Syltherine",
    desc: "Stylish cafe chair",
    price: 2900000,
    oldPrice: 3500000,
    badge: "-30%",
  },
  {
    id: 2,
    img: "/img/prod/prod2.jpg",
    name: "Leviosa",
    desc: "Stylish cafe chair",
    price: 2500000,
    badge: "NEW",
  },
  {
    id: 3,
    img: "/img/prod/prod3.jpg",
    name: "Lolito",
    desc: "Luxury big sofa",
    price: 7000000,
    oldPrice: 14000000,
    badge: "-50%",
  },
  {
    id: 4,
    img: "/img/prod/prod4.jpg",
    name: "Respira",
    desc: "Outdoor bar table and stool",
    price: 500000,
    badge: "NEW",
  },
  {
    id: 5,
    img: "/img/prod/prod5.jpg",
    name: "Grifo",
    desc: "Night lamp",
    price: 1500000,
  },
  {
    id: 6,
    img: "/img/prod/prod6.jpg",
    name: "Muggo",
    desc: "Small mug",
    price: 150000,
    badge: "-10%",
  },
  {
    id: 7,
    img: "/img/prod/prod7.jpg",
    name: "Pingky",
    desc: "Cute bed set",
    price: 7000000,
    oldPrice: 14000000,
    badge: "-50%",
  },
  {
    id: 8,
    img: "/img/prod/prod8.jpg",
    name: "Potty",
    desc: "Minimalist flower pot",
    price: 500000,
  },
  {
    id: 9,
    img: "/img/prod/prod1.jpg",
    name: "Syltherine Premium",
    desc: "Leather cafe chair",
    price: 3200000,
  },
  {
    id: 10,
    img: "/img/prod/prod2.jpg",
    name: "Leviosa Soft",
    desc: "Comfort chair",
    price: 2800000,
  },
  {
    id: 11,
    img: "/img/prod/prod3.jpg",
    name: "Lolito Compact",
    desc: "Luxury mini sofa",
    price: 5000000,
  },
  {
    id: 12,
    img: "/img/prod/prod4.jpg",
    name: "Respira Green",
    desc: "Outdoor table",
    price: 650000,
  },

  {
    id: 13,
    img: "/img/prod/prod5.jpg",
    name: "Grifo Wood",
    desc: "Wooden desk lamp",
    price: 1800000,
  },
  {
    id: 14,
    img: "/img/prod/prod6.jpg",
    name: "Muggo XL",
    desc: "Large mug",
    price: 200000,
  },
  {
    id: 15,
    img: "/img/prod/prod7.jpg",
    name: "Pink Bed",
    desc: "Kids bedroom set",
    price: 9000000,
  },
  {
    id: 16,
    img: "/img/prod/prod8.jpg",
    name: "Potty Green",
    desc: "Modern design pot",
    price: 700000,
  },
  {
    id: 17,
    img: "/img/prod/prod1.jpg",
    name: "Syltherine Classic",
    desc: "Wood chair",
    price: 2000000,
    badge: "NEW",
  },
  {
    id: 7,
    img: "/img/prod/prod7.jpg",
    name: "Pingky",
    desc: "Cute bed set",
    price: 7000000,
    oldPrice: 14000000,
    badge: "-50%" ,
  },
  {
    id: 8,
    img: "/img/prod/prod8.jpg",
    name: "Potty",
    desc: "Minimalist flower pot",
    price: 500000,
  },
  {
    id: 9,
    img: "/img/prod/prod1.jpg",
    name: "Syltherine Premium",
    desc: "Leather cafe chair",
    price: 3200000,
  },
  {
    id: 10,
    img: "/img/prod/prod2.jpg",
    name: "Leviosa Soft",
    desc: "Comfort chair",
    price: 2800000,
  },
  {
    id: 11,
    img: "/img/prod/prod3.jpg",
    name: "Lolito Compact",
    desc: "Luxury mini sofa",
    price: 5000000,
  },
  {
    id: 12,
    img: "/img/prod/prod4.jpg",
    name: "Respira Green",
    desc: "Outdoor table",
    price: 650000,
  },

  {
    id: 13,
    img: "/img/prod/prod5.jpg",
    name: "Grifo Wood",
    desc: "Wooden desk lamp",
    price: 1800000,
  },
  {
    id: 14,
    img: "/img/prod/prod6.jpg",
    name: "Muggo XL",
    desc: "Large mug",
    price: 200000,
  },
  {
    id: 15,
    img: "/img/prod/prod7.jpg",
    name: "Pink Bed",
    desc: "Kids bedroom set",
    price: 9000000,
  },
  {
    id: 16,
    img: "/img/prod/prod8.jpg",
    name: "Potty Green",
    desc: "Modern design pot",
    price: 700000,
  },
  {
    id: 17,
    img: "/img/prod/prod1.jpg",
    name: "Syltherine Classic",
    desc: "Wood chair",
    price: 2000000,
    badge: "NEW",
  },
  {
    id: 18,
    img: "/img/prod/prod2.jpg",
    name: "Leviosa Black",
    desc: "Luxury matte chair",
    price: 3000000,
  },
  {
    id: 19,
    img: "/img/prod/prod3.jpg",
    name: "Lolito Fabric",
    desc: "Fabric sofa",
    price: 6000000,
    badge: "-20%" ,
  },
  {
    id: 20,
    img: "/img/prod/prod4.jpg",
    name: "Respira Bamboo",
    desc: "Eco-friendly table",
    price: 550000,
  },
];
