export const products = [
  {
    id: 1,
    img: "/img/prod/prod1.jpg",
    name: "Syltherine",
    desc: "Stylish cafe chair",
    price: "Rp 2.500.000",
    oldPrice: "Rp 3.500.000",
    badge: "-30%",
  },
  {
    id: 2,
    img: "/img/prod/prod2.jpg",
    name: "Leviosa",
    desc: "Stylish cafe chair",
    price: "Rp 2.500.000",
    badge: "NEW",
  },
  {
    id: 3,
    img: "/img/prod/prod3.jpg",
    name: "Lolito",
    desc: "Luxury big sofa",
    price: "Rp 7.000.000",
    oldPrice: "Rp 14.000.000",
    badge: "-50%",
  },
  {
    id: 4,
    img: "/img/prod/prod4.jpg",
    name: "Respira",
    desc: "Outdoor bar table and stool",
    price: "Rp 500.000",
    badge: "NEW",
  },
  {
    id: 5,
    img: "/img/prod/prod5.jpg",
    name: "Grifo",
    desc: "Night lamp",
    price: "Rp 1.500.000",
  },
  {
    id: 6,
    img: "/img/prod/prod6.jpg",
    name: "Muggo",
    desc: "Small mug",
    price: "Rp 150.000",
    badge: "-10%",
  },
  {
    id: 7,
    img: "/img/prod/prod7.jpg",
    name: "Pingky",
    desc: "Cute bed set",
    price: "Rp 7.000.000",
    oldPrice: "Rp 14.000.000",
    badge: "-50%",
  },
  {
    id: 8,
    img: "/img/prod/prod8.jpg",
    name: "Potty",
    desc: "Minimalist flower pot",
    price: "Rp 500.000",
  },
  {
    id: 9,
    img: "/img/prod/prod1.jpg",
    name: "Syltherine Premium",
    desc: "Leather cafe chair",
    price: "Rp 3.200.000",
  },
  {
    id: 10,
    img: "/img/prod/prod2.jpg",
    name: "Leviosa Soft",
    desc: "Comfort chair",
    price: "Rp 2.800.000",
  },
  {
    id: 11,
    img: "/img/prod/prod3.jpg",
    name: "Lolito Compact",
    desc: "Luxury mini sofa",
    price: "Rp 5.000.000",
  },
  {
    id: 12,
    img: "/img/prod/prod4.jpg",
    name: "Respira Green",
    desc: "Outdoor table",
    price: "Rp 650.000",
  },

  {
    id: 13,
    img: "/img/prod/prod5.jpg",
    name: "Grifo Wood",
    desc: "Wooden desk lamp",
    price: "Rp 1.800.000",
  },
  {
    id: 14,
    img: "/img/prod/prod6.jpg",
    name: "Muggo XL",
    desc: "Large mug",
    price: "Rp 200.000",
  },
  {
    id: 15,
    img: "/img/prod/prod7.jpg",
    name: "Pink Bed",
    desc: "Kids bedroom set",
    price: "Rp 9.000.000",
  },
  {
    id: 16,
    img: "/img/prod/prod8.jpg",
    name: "Potty Green",
    desc: "Modern design pot",
    price: "Rp 700.000",
  },
  {
    id: 17,
    img: "/img/prod/prod1.jpg",
    name: "Syltherine Classic",
    desc: "Wood chair",
    price: "Rp 2.000.000",
    badge: "NEW",
  },
  {
    id: 18,
    img: "/img/prod/prod2.jpg",
    name: "Leviosa Black",
    desc: "Luxury matte chair",
    price: "Rp 3.000.000",
  },
  {
    id: 19,
    img: "/img/prod/prod3.jpg",
    name: "Lolito Fabric",
    desc: "Fabric sofa",
    price: "Rp 6.000.000",
    badge: "-20%",
  },
  {
    id: 20,
    img: "/img/prod/prod4.jpg",
    name: "Respira Bamboo",
    desc: "Eco-friendly table",
    price: "Rp 550.000",
  },
];
